version: "3"

services:
  gerrit:
    container_name: jhu_gerrit
    #image: gerritcodereview/gerrit:3.3.2
    #image: gerritcodereview/gerrit:3.2.7
    image: gerritcodereview/gerrit:3.1.11-ubuntu18
    ports:
      - "29418:29418"
      - "8080:8080"
    volumes:
      - /home/$USER/docker_ws/gerrit/etc:/var/gerrit/etc
      - /home/$USER/docker_ws/gerrit/git:/var/gerrit/git
      - /home/$USER/docker_ws/gerrit/db:/var/gerrit/db
      - /home/$USER/docker_ws/gerrit/index:/var/gerrit/index
      - /home/$USER/docker_ws/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://10.8.16.158:8080 
    user: 0:0
   
    #restart: always
    #command: init
    
  cgit:
    container_name: jhu_cgit
    image: clearlinux/cgit:latest
    ports:
      - "8082:80"
    volumes:
      - /home/$USER/docker_ws/gerrit/git:/var/www/cgit

  db:
    image: postgres
    container_name: jhu_postgress
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - /home/$USER/docker_ws/postgresql/data:/var/lib/postgresql/data
