version: "3"

services:
  gerrit:
    container_name: jhu_gerrit
    image: gerritcodereview/gerrit:3.1.11-ubuntu18
    ports:
      - "29418:29418"
      - "8080:8080"
    depends_on:
      - ldap
    volumes:
      - /home/$USER/docker_ws/gerrit/etc:/var/gerrit/etc
      - /home/$USER/docker_ws/gerrit/git:/var/gerrit/git
      - /home/$USER/docker_ws/gerrit/db:/var/gerrit/db
      - /home/$USER/docker_ws/gerrit/index:/var/gerrit/index
      - /home/$USER/docker_ws/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://gerrit.askey.cn:8080 
    user: 0:0
   
    restart: always
    

  ldap:
    container_name: jhu_ldap
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - /home/$USER/docker_ws/ldap/var:/var/lib/ldap
      - /home/$USER/docker_ws/ldap/etc:/etc/ldap/slapd.d
    user: 0:0

  ldap-admin:
    container_name: jhu_ldap_admin
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

  cgit:
    container_name: jhu_cgit
    image: clearlinux/cgit:latest
    ports:
      - "8082:80"
    volumes:
      - /home/$USER/docker_ws/gerrit/git:/var/www/cgit

  smtp:
    container_name: jhu_smtp
    image: namshi/smtp:latest
    ports:
      - "587:25"
    environment:
      - RELAY_NETWORKS=:10.8.0.0/16
    restart: always

  reposync:
    container_name: jhu_reposync
    image: askey/reposync:v1.2
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /home/$USER/docker_ws/opengrok:/home/$USER/opengrok
      - /home/$USER/docker_ws/reposync.gerrit:/home/$USER/reposync.gerrit
      - /home/$USER/jhscript/script/scm/reposync.sh:/home/$USER/reposync.sh

  opengrok:
    container_name: jhu_opengrok
    image: opengrok/docker:1.5.11
    ports:
      - "8081:8080/tcp"
    environment:
      REINDEX: '720'
      NOMIRROR: '1'
    # Volumes store your data between container upgrades
    volumes:
      #- '/home/$USER/:/home/$USER'  # source code
      - '/home/$USER/docker_ws/opengrok/src:/opengrok/src/'  # source code
      - '/home/$USER/docker_ws/opengrok/etc/:/opengrok/etc/'  # folder contains configuration.xml
      - '/home/$USER/docker_ws/opengrok/data/:/opengrok/data/'  # index and other things for source code
